
language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - npm test

after_success:
  - chmod +x travis/publish.sh
  - 'docker build -t ${TRAVIS_REPO_SLUG} .'
  - travis/publish.sh
